### ISSUE TITLE
1.20.1 issue with Fancymenu

### ISSUE THREAD

**Issue by ModernGamingWorld** [malte0811/ServerConfigCleaner#2]
I added this mod to my custom modpack of 700ish mods, and after it loaded, it said it failed to load resources and wouldn't load my custom fancy menu stuff.

Can confirm with the mod active, none of my custom fancy menu stuff works. Once I disable the mod fully, all my fancymenu stuff is working again

**Comment by Keksuccino** [comment]
Please send your `/logs/latest.log` file after loading the pack with FM and seeing the default menu instead of the customized one.

**Comment by ModernGamingWorld** [comment]
[latest.log](https://github.com/user-attachments/files/18232543/latest.log) Like I said, its weird; it only breaks the menu whenever this mod is active

**Comment by Keksuccino** [comment]
Thank you! Okay, I can't find any errors related to FM, so it's probably something related to ServerConfigCleaner that blocks FM loading the layout files maybe? I am pretty sure this needs to be fixed on ServerConfigCleaner's side.

**Comment by Keksuccino** [comment]
But the issue title should be more related to FancyMenu, so people don't create duplicated issues :D

**Comment by ThatGravyBoat** [comment]
There are keys that matched the heuristics but are not sensitive it was in this error message:
> Potentially secret config keys found: ["notenoughwands:general.wandsettings.capturing_wand.allowHostile", "notenoughwands:general.wandsettings.freezing_wand.freezeAllowHostile", "notenoughwands:general.wandsettings.potion_wand.potionAllowHostile"]. Please mark them as either false positives or excluded from sync in the serverconfigcleaner-common.toml

Follow that, I will update the default false positives list so others don't run into it

**Comment by ModernGamingWorld** [comment]
@ThatGravyBoat even adding those to the config, Fancymenu still is broken

**Comment by Keksuccino** [comment]
Well that makes sense, because FM isn't even using Forge's server config 😅

**Comment by ThatGravyBoat** [comment]
Make sure you put them in the correct spot, because when testing I put the mod in various packs and almost all of them included FM

**Comment by ModernGamingWorld** [comment]
The other weird thing is that even after adding those, it won't even let me join a world. You can test using this modpack
https://www.curseforge.com/minecraft/modpacks/monumental-experience/files/6012356

**Comment by ThatGravyBoat** [comment]
> The other weird thing is that even after adding those, it won't even let me join a world. You can test using this modpack [curseforge.com/minecraft/modpacks/monumental-experience/files/6012356](https://www.curseforge.com/minecraft/modpacks/monumental-experience/files/6012356)

I just tested with those lines and it worked fine, heres a copy just incase but it loaded just fine

```toml
#Patterns used to determine suspicious config keys. Capitalization is ignored.
badConfigPatterns = ["host", "username", "password", "secret", "token", "apikey", "webhook", "jdbc", "sql", "redis", "mongodb", "database"]
#Options to exclude from config syncing
#Format: modid:category.configKey
doNotSync = []
#Options that are detected by the badConfigPatterns, but should still be synced
#Format: modid:category.configKey; * allowed at the end of an entry
falsePositives = ["rftoolsbuilder:scanner.locatorUsePerTickHostile", "tombstone:player_death.ghostly_shape_duration", "mahoutsukai:secret.*", "create:logistics.seatHostileMobs", "tombstone:general.ghostly_shape_duration", "skinnedlanterns:lanterns.ghost_soul_lantern", "skinnedlanterns:lanterns.ghost_lantern", "goblinsanddungeons:general.Super Secret Settings", "moblassos:hostile_damage_rate", "moblassos:hostile_mob_health", "moblassos:hostile_lasso_time", "notenoughwands:general.wandsettings.capturing_wand.allowHostile", "notenoughwands:general.wandsettings.freezing_wand.freezeAllowHostile", "notenoughwands:general.wandsettings.potion_wand.potionAllowHostile"]
#A somewhat obfuscated list of known options containing secrets.
#Ignore unless you know what you are doing.
doNotSyncHashes = []
```
